table All_Committed_Task
	lineageTag: 5c6267a5-5968-426f-9fa3-2d3bc0ead694

	column 'data.isAutoCommit'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 68a7a667-e2d9-4282-8c93-d37d7017cbbd
		summarizeBy: none
		sourceColumn: data.isAutoCommit

		annotation SummarizationSetBy = Automatic

	column committedTimestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 858697af-0dd4-47fb-8fbc-1e00d5f38f08
		summarizeBy: none
		sourceColumn: committedTimestamp

		variation Variation
			isDefault
			relationship: 37131786-2540-4adf-93fc-754ab2ace9e8
			defaultHierarchy: LocalDateTable_bb3685d8-aa71-4776-8d05-d1bc2b4cc833.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column committedStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a9395a33-b856-4f63-b0fe-51dbdbec47f5
		summarizeBy: none
		sourceColumn: committedStartDate

		variation Variation
			isDefault
			relationship: 0e68b874-dfd2-4f5f-9ad7-f123d818f71d
			defaultHierarchy: LocalDateTable_a644e0d2-9143-4e23-a616-480c26f6fbdd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column committedEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c1329d89-9da4-4cf8-92ba-cda2c99e34b5
		summarizeBy: none
		sourceColumn: committedEndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column activitiesGuid
		dataType: string
		lineageTag: 5dd8540a-d5f8-43c5-acbe-dc0915ddae4a
		summarizeBy: none
		sourceColumn: activitiesGuid

		annotation SummarizationSetBy = Automatic

	column 'Project Name'
		dataType: string
		lineageTag: 735e2722-d25a-4ab0-9964-a02b918172fa
		summarizeBy: none
		sourceColumn: Project Name

		annotation SummarizationSetBy = Automatic

	column Committed_WeeknYear
		dataType: int64
		formatString: 0
		lineageTag: a83a0660-0b1f-43bc-920b-5687612ae818
		summarizeBy: sum
		sourceColumn: Committed_WeeknYear

		annotation SummarizationSetBy = Automatic

	column CommittedWeek-Year
		dataType: string
		lineageTag: 82b09de6-8686-4e84-a7e8-25f934297ede
		summarizeBy: none
		sourceColumn: CommittedWeek-Year

		annotation SummarizationSetBy = Automatic

	column taskId
		dataType: int64
		formatString: 0
		lineageTag: 1e1dd383-ed05-40bb-8f7f-549b28001de4
		summarizeBy: count
		sourceColumn: taskId

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: efe9eded-9fe9-4454-ab59-156a8f9bb199
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column owner
		dataType: string
		lineageTag: 929f6cd6-dfdb-49b3-8f9c-86a3487002ae
		summarizeBy: none
		sourceColumn: owner

		annotation SummarizationSetBy = Automatic

	column guid
		dataType: string
		lineageTag: 11553eaf-ed01-4821-b452-3d944ecda639
		summarizeBy: none
		sourceColumn: guid

		annotation SummarizationSetBy = Automatic

	column actualStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a2529d23-8084-4340-8c3e-588a7a5f33c8
		summarizeBy: none
		sourceColumn: actualStartDate

		variation Variation
			isDefault
			relationship: ce56a960-99af-4c56-a73d-a791a88dec60
			defaultHierarchy: LocalDateTable_ddec0afa-e4d3-4514-b085-9fbd9664ae41.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column actualEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d1c00758-6ed6-4950-ac1f-53d5d2946b7e
		summarizeBy: none
		sourceColumn: actualEndDate

		variation Variation
			isDefault
			relationship: bf09944f-6324-4b0c-aa8d-5f3e9b697947
			defaultHierarchy: LocalDateTable_59f97a1e-2458-4699-a3fa-f9747a24652c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column trade
		dataType: string
		lineageTag: 5ed9148b-6b3c-4963-b76b-1543278bc902
		summarizeBy: none
		sourceColumn: trade

		annotation SummarizationSetBy = Automatic

	column plannedStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6a499160-14f1-4235-be92-41a45272eeda
		summarizeBy: none
		sourceColumn: plannedStartDate

		variation Variation
			isDefault
			relationship: adeb4719-7aea-4c93-ab68-eb2c67c474ee
			defaultHierarchy: LocalDateTable_eac2ee0d-f16a-47ec-8877-b529bc4ad5ab.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column plannedEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e5bba371-114d-4b7d-8acf-ab426d4063ab
		summarizeBy: none
		sourceColumn: plannedEndDate

		variation Variation
			isDefault
			relationship: 17f294bb-7117-49b6-be76-8c1ffa77540f
			defaultHierarchy: LocalDateTable_ccbb3d65-5d4a-431c-b521-33693042e405.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column status
		dataType: string
		lineageTag: 13d75a9d-d510-4f89-9f27-d428c99747f8
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column taskName
		dataType: string
		lineageTag: 3d96389f-99fb-420d-96ac-d74ee6c65482
		summarizeBy: none
		sourceColumn: taskName

		annotation SummarizationSetBy = Automatic

	column historyDateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 806977d7-04be-4ff1-b5fc-6401a7a20430
		summarizeBy: none
		sourceColumn: historyDateTime

		variation Variation
			isDefault
			relationship: ffebae28-7727-4b54-9570-f038cb400a90
			defaultHierarchy: LocalDateTable_a8432508-0b6b-4f10-aec2-49c0afc781d6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column activityHistory
		dataType: string
		lineageTag: c24f26de-5108-4b56-9261-aed555c9821c
		summarizeBy: none
		sourceColumn: activityHistory

		annotation SummarizationSetBy = Automatic

	column 'Reasons Category'
		dataType: string
		lineageTag: 562e4cd4-1e31-4ad2-9c50-e33774f06160
		summarizeBy: none
		sourceColumn: Reasons Category

		annotation SummarizationSetBy = Automatic

	column 'Reasons for Variance'
		dataType: string
		lineageTag: 8789fb4b-8488-4482-bb87-815aa2752fcf
		summarizeBy: none
		sourceColumn: Reasons for Variance

		annotation SummarizationSetBy = Automatic

	column Planned_Week-Year
		dataType: string
		lineageTag: 121340ea-6408-48f1-b175-1df0dae836b7
		summarizeBy: none
		sourceColumn: Planned_Week-Year

		annotation SummarizationSetBy = Automatic

	column Actual_Week-Year
		dataType: string
		lineageTag: 01f93227-06f5-4286-96d1-654a4e8a8551
		summarizeBy: none
		sourceColumn: Actual_Week-Year

		annotation SummarizationSetBy = Automatic

	column Custom_CommittedPPC
		dataType: string
		lineageTag: 0e89fc78-dfde-46e6-b507-f6b3bbbce387
		summarizeBy: none
		sourceColumn: Custom_CommittedPPC

		annotation SummarizationSetBy = Automatic

	column SubProject
		dataType: string
		lineageTag: 8bc8726a-539d-4c8c-b894-b80c3b9032ad
		summarizeBy: none
		sourceColumn: SubProject

		annotation SummarizationSetBy = Automatic

	partition All_Committed_Task = m
		mode: import
		queryGroup: MasterTables
		source =
				let
				    Source = Table.Combine({Mercury_Committed, DPFCampus_Commiited,ExceptDPFCampus_C}),
				     #"Filtered Rows4" = Table.SelectRows(Source, each ([committedTimestamp] <> null)),
				    #"Renamed Columns2" = Table.RenameColumns(#"Filtered Rows4",{{"Sub Project", "SubProject"}}),
				    Custom1 = Table.ReplaceValue(#"Renamed Columns2",each [SubProject],each if [SubProject] = ""  then [Project Name] else [SubProject],Replacer.ReplaceValue,{"SubProject"}),
				    #"Changed Type2" = Table.TransformColumnTypes(Custom1,{{"committedTimestamp", type datetimezone}, {"committedStartDate", type date}, {"committedEndDate", type date}}),
				    CommittedWeeknYear = Table.AddColumn(#"Changed Type2", "Committed_WeeknYear", each (Date.Year([committedEndDate])) * 10000 + ( if Number.RoundDown((Date.DayOfYear([committedEndDate])-(Date.DayOfWeek([committedEndDate], Day.Monday)+1)+10)/7)=0
				        then Number.RoundDown((Date.DayOfYear(#date(Date.Year([committedEndDate])-1,12,31))-(Date.DayOfWeek(#date(Date.Year([committedEndDate])-1,12,31), Day.Monday)+1)+10)/7)
				        else if (Number.RoundDown((Date.DayOfYear([committedEndDate])-(Date.DayOfWeek([committedEndDate], Day.Monday)+1)+10)/7)=53 and (Date.DayOfWeek(#date(Date.Year([committedEndDate]),12,31), Day.Monday)+1<4))
				        then 1 else Number.RoundDown((Date.DayOfYear([committedEndDate])-(Date.DayOfWeek([committedEndDate], Day.Monday)+1)+10)/7)) * 100,  Int64.Type),
				    #"CommittedWeek-Year" = Table.AddColumn(CommittedWeeknYear, "CommittedWeek-Year", each Text.From(Date.Year([committedEndDate])) & "-" & Text.PadStart( Text.From(  if Number.RoundDown((Date.DayOfYear([committedEndDate])-(Date.DayOfWeek([committedEndDate], Day.Monday)+1)+10)/7)=0
				        then Number.RoundDown((Date.DayOfYear(#date(Date.Year([committedEndDate])-1,12,31))-(Date.DayOfWeek(#date(Date.Year([committedEndDate])-1,12,31), Day.Monday)+1)+10)/7)
				        else if (Number.RoundDown((Date.DayOfYear([committedEndDate])-(Date.DayOfWeek([committedEndDate], Day.Monday)+1)+10)/7)=53 and (Date.DayOfWeek(#date(Date.Year([committedEndDate]),12,31), Day.Monday)+1<4))
				        then 1 else Number.RoundDown((Date.DayOfYear([committedEndDate])-(Date.DayOfWeek([committedEndDate], Day.Monday)+1)+10)/7) ), 2, "0"), type text ),
				    MergedExpanded = Table.ExpandTableColumn(
				        Table.NestedJoin(
				            #"CommittedWeek-Year",
				            {"activitiesGuid"},
				            MasterTable,
				            {"guid"},
				            "visilean (2)",
				            JoinKind.LeftOuter
				        ),
				        "visilean (2)",
				        {
				            "taskId", "location", "owner", "guid",
				            "actualStartDate", "actualEndDate",
				            "trade", "plannedStartDate", "plannedEndDate",
				            "status", "taskName", "historyDateTime","activityHistory",
				            "Reasons Category", "Reasons for Variance", "Planned_Week-Year","Actual_Week-Year"
				        },
				        {
				            "taskId", "location", "owner", "guid",
				            "actualStartDate", "actualEndDate",
				            "trade", "plannedStartDate", "plannedEndDate",
				            "status", "taskName", "historyDateTime","activityHistory",
				            "Reasons Category", "Reasons for Variance", "Planned_Week-Year","Actual_Week-Year"
				        }
				    ),
				    #"Added Custom" = Table.AddColumn(
				    MergedExpanded,
				    "Custom_CommittedPPC",
				    each
				        if [#"Actual_Week-Year"] <> null then
				            if [#"Actual_Week-Year"] = [#"CommittedWeek-Year"] then "Yes" else "No"
				        else
				            "No"
				)
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

