table ProjectList
	lineageTag: 696697ec-a99e-4da4-b282-0364cb3d6d9c

	column ProjectList
		dataType: string
		lineageTag: d0c230a0-c87d-444c-9861-af428d55f46f
		summarizeBy: none
		sourceColumn: ProjectList
		sortByColumn: 'Sr.No'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 06edd6cb-903d-4fff-8061-116c2cb680f9
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 176906bf-0db8-47e5-b890-052446f432bd
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column Logo
		dataType: string
		lineageTag: f8905a6a-fa9b-40d4-a1dc-6823c5871878
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: Logo

		annotation SummarizationSetBy = Automatic

	column Contractor
		dataType: string
		lineageTag: 36b5aeb8-afd7-48a7-989d-77bb189a6b88
		summarizeBy: none
		sourceColumn: Contractor

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: a257d19c-c360-4a62-a3eb-e4f3479f80ba
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 904417d4-8834-4529-b0fd-55dd591c971a
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'Sr.No'
		dataType: int64
		formatString: 0
		lineageTag: 028322c0-6157-458c-ae48-43d08bfe723c
		summarizeBy: sum
		sourceColumn: Sr.No

		annotation SummarizationSetBy = Automatic

	partition ProjectList = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("1ZZbb9owFMe/SsVzIc4VqISqAOHWBcKlhdJVyE1MSEmcYDt09LPtbV9sdkK1dWurda2K+hDl+MSxfznH/3NydVWQC8eFptM6asAoSSkfOPZRm8Rpws0GwozA8MhKSZwg7mgjEkG841aLQLxepoRxe8wgYcjj1oqxhJ5IEsIu2SXcV2Q3GJR8yiAL3JIbR1IQQR/R002NPzkx+1617U4uLJR4rjNjjYoSlntRZDubc2cCN5eDRas7t1nif00BUAxauD6+Kihi/5GpAH63EXFTsvs42OFYby4m/Wrr0ukuiRV3NzPF7fbUy949iKdntOP7d7/DqjmsrhX18tt4s+U0bpxPgfYOS+k5mVx9h7WMfC1V/QwpEXkw7bFsPILNIY/6MWErPuwjtkIkhNgTojAjyhDxYHQA3IrAHI2ByFd7bP1CtQNvH0lXBNeGhKIgDNGTjBHyAlgKA9fDGZgX0RxO2ipSQzdA3Ry2vTqZk83dZJ0MJT4p4bkqhrEfLxQAxPW0E0iyoQJD1wxZBtWy5FO08FDKqLsS8VuIyaeopshaWauohlbOv25bu0EM5jarLQLPJevJnNCoTYrawNpZw2QeYVh1Lqblb04v6A42kzN6O6xkUZGF+h1zJIuwWJsUYvpsZBxIAnqAzMmiuNpmUysJvXb5CXJj/CflOIEBztLnkdzx1nLapl+8dHpv3/rNzsweYEs3l/WROeuo2+XSH9/e7x6VU1nU04bTAepLemgiHEGyFlO5G6/4tvgQIRWQ/fog6wEcLdimQpPmkgQuFI9gQOKb4JH1N+Ny/2ZGdZcUeVoYr1VSmoQx9KikAEWXgCZljbAo63IpwX6+v7YvHvLnKB6ZPIRMnuR9RicNrvIQMfRxlPv+UXmPFimXH1SnvkJ1b/7mV8tO1PXm+fifW2bzx3dKUejFZHmIgyR+E+qNPnjhID0EtQ6Ji8IYwwNwVvfnXfuftlC4vv4J", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Sr.No = _t, ProjectList = _t, Contractor = _t, Region = _t, Country = _t, City = _t, Status = _t, Logo = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ProjectList", type text}, {"Sr.No", Int64.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Sr.No", Order.Ascending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows", each ([ProjectList] <> "AMS11" and [ProjectList] <> "BCN01" and [ProjectList] <> "FRA87" and [ProjectList] <> "MAD4.3" and [ProjectList] <> "PAR11"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

