table Tolerance_Limits
	lineageTag: a919473b-a3bb-43e0-a005-346e13037407

	column 'Metric (New Name)'
		dataType: string
		lineageTag: 986c80d4-d1b6-48b4-b62b-b8467bf0031e
		summarizeBy: none
		sourceColumn: Metric (New Name)

		annotation SummarizationSetBy = Automatic

	column 'Green ✅ (Good)'
		dataType: string
		lineageTag: 7859ec62-e5cd-4ea9-b497-4502d0cf2ce0
		summarizeBy: none
		sourceColumn: Green ✅ (Good)

		annotation SummarizationSetBy = Automatic

	column 'Orange ⚠️ (Watch)'
		dataType: string
		lineageTag: c043957e-bc69-4ad0-8e22-1c38a7dc7712
		summarizeBy: none
		sourceColumn: Orange ⚠️ (Watch)

		annotation SummarizationSetBy = Automatic

	column 'Red 🔴 (Critical)'
		dataType: string
		lineageTag: ff0991d9-2218-4f27-a059-dcedeab3360c
		summarizeBy: none
		sourceColumn: Red 🔴 (Critical)

		annotation SummarizationSetBy = Automatic

	partition Tolerance_Limits = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZZJNasMwEIWvMhgMCcRFriM7XQZ7WYgpLV24Xoh4CCKKXGzZkF23XfcK7cVyktqS/JNkpxn43rz3UJY574hHcYZUMCmxgO1e8ZYrjrWzci7ff+AT0r0ogcvXjx0+GkKCPVDi5KvMcTULcXn6FKgQFmkaLy28IW73CqmGoyd3gkPqWnq6CAkKdsZCw79ANWvu0hFFPfTotj08GASSpmKKlxIWCTvXy0EAim6aiQzzKGQWxkdcylpVjEtVw67FqmjQ6pjrvlEJyMxKP9zTL1iXou3K3EnvlZ/QlhFpcm2aDOdlrMks0aQEz+xwnSgaEmy0yCO5STQsjKc3Kbg8dj5m5qyQSRH4xss8Umi9DB9irNaDEPrPAr3Lu4Y9/9bLsMjzfw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Metric (New Name)" = _t, #"Green ✅ (Good)" = _t, #"Orange ⚠️ (Watch)" = _t, #"Red 🔴 (Critical)" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric (New Name)", type text}, {"Green ✅ (Good)", type text}, {"Orange ⚠️ (Watch)", type text}, {"Red 🔴 (Critical)", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Metric (New Name)", "Metric (New Name)"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

